name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Sign APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Generate debug keystore
        run: |
          mkdir -p .github/keystore
          keytool -genkey -v -keystore .github/keystore/debug.keystore \
            -alias androiddebugkey -storepass android -keypass android \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace --warning-mode all

      - name: Install zipalign and apksigner
        run: |
          sudo apt-get update
          sudo apt-get install -y zipalign
          echo "Available build-tools:"
          ls $ANDROID_HOME/build-tools
          export BUILD_TOOLS_VERSION=$(ls $ANDROID_HOME/build-tools | sort -r | head -n 1)
          echo "Using build-tools version: $BUILD_TOOLS_VERSION"

      - name: Zipalign and Sign APK with apksigner
        run: |
          ZIPALIGN=$(find $ANDROID_HOME/build-tools -name zipalign | sort -r | head -n 1)
          APKSIGNER=$(find $ANDROID_HOME/build-tools -name apksigner | sort -r | head -n 1)
          $ZIPALIGN -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk aligned.apk
          $APKSIGNER sign --ks .github/keystore/debug.keystore \
            --ks-pass pass:android \
            --key-pass pass:android \
            --out app-release-signed.apk \
            aligned.apk

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: WhatsAppCleanerPro-Signed-APK
          path: app-release-signed.apk
