name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Generate debug keystore
        run: |
          mkdir -p .github/keystore
          keytool -genkey -v -keystore .github/10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Build Release APK and extract errors
        id: build
        continue-on-error: true
        shell: bash
        run: |
          set -o pipefail
          ./gradlew assembleRelease --stackCaused by|Execution failed for task|resource linking failed|resource .+ not found" build_output.txt > errors_only.txt || true

          if [ ! -s errors_only.txt ]; then
            echo "No error patterns detected in the last 1000 lines." > errors_only.txt
            tail -n -${{ github.run_number }}
          path: errors_only.txt
          retention-days: 7

      - name: Check APK existence
        id: check_apk
        run: |
          if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
            echo "APK_EXISTS=true actions/upload-artifact@v4
        with:
          name: WhatsAppCleanerPro-Release-APK-${{ github.run_number }}
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 30
