name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Clean Build and Sign APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Generate debug keystore
        run: |
          mkdir -p .github/keystore
          keytool -genkey -v -keystore .github/keystore/debug.keystore \
            -alias androiddebugkey -storepass android -keypass android \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Clean and refresh dependencies
        run: |
          ./gradlew clean --refresh-dependencies --stacktrace
          ./gradlew --stop

      - name: Generate dependency report
        run: ./gradlew :app:dependencies > dependencies.txt

      - name: Build Debug APK first
        run: |
          ./gradlew assembleDebug --stacktrace --info || {
            echo "Debug build failed. See dependencies.txt for help."
            exit 1
          }

      - name: Build Release APK with logging
        id: build
        continue-on-error: true
        shell: bash
        run: |
          echo "Starting release build at $(date)"
          ./gradlew assembleRelease --stacktrace --info > build_output.txt 2>&1
          BUILD_SUCCESS=$?

          {
            echo "=== Build Errors & Warnings ==="
            awk '/error:|warning:|^e:|^w:|failed|exception|undefined|not found|duplicate|caused by/i' build_output.txt \
              | sed -E 's/^\s+//g' \
              | sed -E 's/^.*//g' \
              | sort | uniq
            echo ""
            echo "=== Last 50 Lines of Gradle Output ==="
            tail -n 50 build_output.txt
          } > errors_only.txt

          exit $BUILD_SUCCESS

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Logs-${{ github.run_number }}
          path: |
            errors_only.txt
            build_output.txt
            dependencies.txt
            app/build/reports/
            app/build/outputs/logs/
            app/build/outputs/apk/release/
          retention-days: 7

      - name: Check APK existence
        id: check_apk
        if: steps.build.outcome == 'success'
        run: |
          if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
            echo "APK_EXISTS=true" >> $GITHUB_ENV
          else
            echo "APK file not found!"
            echo "APK_EXISTS=false" >> $GITHUB_ENV
            exit 1
          fi

      - name: Zipalign and Sign APK
        if: env.APK_EXISTS == 'true'
        run: |
          ZIPALIGN=$(find $ANDROID_HOME/build-tools -name zipalign | sort -r | head -n 1)
          APKSIGNER=$(find $ANDROID_HOME/build-tools -name apksigner | sort -r | head -n 1)

          echo "Using zipalign: $ZIPALIGN"
          echo "Using apksigner: $APKSIGNER"

          $ZIPALIGN -v -p 4 app/build/outputs/apk/release/app-release.apk aligned.apk

          $APKSIGNER sign --ks .github/keystore/debug.keystore \
            --ks-pass pass:android \
            --key-pass pass:android \
            --out app-release-signed.apk \
            aligned.apk

          $APKSIGNER verify --verbose app-release-signed.apk

      - name: Upload final signed APK
        if: env.APK_EXISTS == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: WhatsAppCleanerPro-Signed-APK-${{ github.run_number }}
          path: app-release-signed.apk
          retention-days: 30

      - name: Upload debug APK if release failed
        if: env.APK_EXISTS != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Debug-APK-${{ github.run_number }}
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 7
