name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Generate debug keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android \
            -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"
          mkdir -p .github/keystore
          mv debug.keystore .github/keystore/debug.keystore

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build signed release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: List built APKs
        run: ls -la app/build/outputs/apk/release/

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: WhatsAppCleanerPro-Signed-APK
          path: app/build/outputs/apk/release/app-release.apk
