name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Generate debug keystore
        run: |
          mkdir -p .github/keystore
          keytool -genkey -v -keystore .github/keystore/debug.keystore \
            -alias androiddebugkey -storepass android -keypass android \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Debug: List keystore
        run: ls -la .github/keystore

      - name: Build release APK using debug signing
        run: ./gradlew assembleRelease --stacktrace --warning-mode all

      - name: Verify APK location
        run: ls -R app/build/outputs/apk/

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: WhatsAppCleanerPro-APK
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload generated debug keystore
        uses: actions/upload-artifact@v4
        with:
          name: debug-keystore
          path: .github/keystore/debug.keystore
