name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Clean Build and Sign APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: $.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Generate debug keystore
        run: |
          mkdir -p .github/keystore
          keytool -genkey -v -keystore .github/keystore dependencies
        run: ./gradlew clean --refresh-dependencies

      - name: Build APK and save full log
        run: |
          ./gradlew assembleRelease --stacktrace --debug --info > full_build_log.txt 2>&1 || (
            echo "===== BUILD FAILED. Showing last 100 lines of '(^e: .*\.(kt|java):[0-9]+:[0-9]+|error:|Unresolved reference:|cannot find symbol|Exception|Caused by:|Execution failed for task|resource linking failed|resource .+ not found)' full_build_log.txt > errors_only.txt || true full_build_log.txt for more details." > errors_only.txt
          fi

      - name: Upload build log (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Failure-Log
          path: |
            full_build_log.txt
            and Sign APK
        run: |
          ZIPALIGN=$(find $ANDROID_HOME/build-tools -name zipalign | sort -r | head -n 1)
          APKSIGNER=$(find $ANDROID_HOME/build-tools -name apksigner | sort -r | head -n 1)
          echo "Using zipalign: $ZIPALIGN"
          echo "Using apksigner: $APKSIGNER"
          $ZIPALIGN -v - --ks .github/keystore/debug.keystore \
            --ks-pass pass:android \
            --key-pass pass:android \
            --out app-release-signed.apk \
            aligned.apk

      - name: Upload final signed APK
        uses: actions/upload-artifact@v4
        with:
          name:: app-release-signed.apk
